# Generated by Django 3.1.2 on 2020-10-14 11:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0004_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('county', models.CharField(max_length=255, verbose_name='Страна')),
                ('year', models.CharField(max_length=255, verbose_name='Год')),
                ('studio', models.CharField(max_length=255, verbose_name='Студия')),
                ('voiced', models.TextField(verbose_name='Роли озвучивали')),
                ('timing', models.TextField(verbose_name='Тайминг и работа над звуком')),
                ('img', models.ImageField(height_field=500, upload_to='', verbose_name='Обложка', width_field=337)),
                ('upload_data', models.DateTimeField(default=datetime.datetime(2020, 10, 14, 14, 36, 45, 294639))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Категория')),
                ('genres', models.ManyToManyField(to='category.Genre', verbose_name='Жанры')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.type', verbose_name='Тип')),
            ],
        ),
    ]
