# Generated by Django 3.1.2 on 2020-10-14 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_data',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 14, 43, 19, 174211)),
        ),
    ]
