# Generated by Django 3.1.2 on 2020-10-14 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20201014_1520'),
        ('posts', '0002_auto_20201014_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_data',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 15, 20, 57, 901192)),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(verbose_name='Сезон')),
                ('episode', models.IntegerField(verbose_name='Серия')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Плеер')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
