# Generated by Django 3.1.2 on 2020-10-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201014_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload_data',
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='posts/imgs/', verbose_name='Обложка'),
        ),
    ]
