# Generated by Django 3.1.2 on 2020-10-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201014_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='county',
            new_name='country',
        ),
    ]
