# Generated by Django 3.1.2 on 2020-12-09 20:34

from django.db import migrations


def link_studios(apps, schema_editor):
    Studio = apps.get_model('posts', 'Studio')
    Post = apps.get_model('posts', 'Post')
    for post in Post.objects.all():
        studio, created = Studio.objects.get_or_create(name=post.studio)
        post.studio_link = studio
        post.save()


def unlink_studio(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    for post in Post.objects.all():
        post.studio = str(post.studio_link)
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20201209_2350'),
    ]

    operations = [
        migrations.RunPython(link_studios, unlink_studio)
    ]
