# Generated by Django 3.1.2 on 2020-12-09 20:44

from django.db import migrations


def link_voiced(apps, schema_editor):
    Dubber = apps.get_model('posts', 'Dubber')
    Post = apps.get_model('posts', 'Post')
    for post in Post.objects.all():
        names = post.voiced.split(", ")
        for name in names:
            voiced, created = Dubber.objects.get_or_create(name=name)
            post.voiced_link.add(voiced)
        post.save()


def unlink_voiced(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    for post in Post.objects.all():
        result = post.voiced_link.order_by('name')
        voiced = [str(dubber) for dubber in result]
        post.voiced = ", ".join(voiced)
        post.save()



class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_transfer_studio'),
    ]

    operations = [
        migrations.RunPython(link_voiced, unlink_voiced)
    ]
