# Generated by Django 3.1.2 on 2020-12-09 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_transfer_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='post',
            name='timing',
        ),
        migrations.RemoveField(
            model_name='post',
            name='voiced',
        ),
    ]
