# Generated by Django 3.1.2 on 2020-12-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20201210_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='studio_link',
            new_name='studio',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='timing_link',
            new_name='timing',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='voiced_link',
            new_name='voiced',
        ),
    ]
