# Generated by Django 3.1.2 on 2020-12-10 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20201210_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 17, 7, 21, 578169)),
        ),
    ]
