# Generated by Django 3.1.2 on 2020-10-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Плеер', 'verbose_name_plural': 'Плееры'},
        ),
    ]
