# Generated by Django 3.1.2 on 2020-10-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Уникальное название')),
                ('display_name', models.TextField(verbose_name='Отображаемое название')),
            ],
        ),
    ]
