# Generated by Django 3.1.2 on 2020-10-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
