# Generated by Django 3.1.2 on 2020-12-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20201014_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(default=True, verbose_name='Отображать на главной'),
        ),
    ]
